#!/bin/bash
#PBS -l mem=4gb,nodes=1:ppn=8,walltime=24:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q small

set -e
set -o pipefail

# This script runs SNPMeta on the 50k snps dataset

# Dependencies
module load python3/3.7.1_anaconda
module load emboss/6.6.0
export PATH=${PATH}:/panfs/roc/groups/9/morrellp/liux1299/Software/SNPMeta

# User provided input arguments
FASTA=/panfs/roc/groups/9/morrellp/shared/Datasets/Genotyping/Contextual_Sequences/barley_50k/snpmeta_50k_snps.fasta
EMAIL=liux1299@um.edu
OUT_FILENAME=50k_snpmeta_output.txt
OUT_DIR=/panfs/roc/groups/9/morrellp/liux1299/GitHub/morex_reference/morex_v2/data

# Run program
SNPMeta.py -f ${FASTA} -i -a ${EMAIL} --outfmt tabular > ${OUT_DIR}/${OUT_FILENAME}
